@startuml Singleton

title 单例模式：HeroAircraft

!theme plain

class HeroAircraft <<Singleton>> {
    - {static} instance: HeroAircraft
    - Hpmax: int
    ---
    - HeroAircraft(int, int, int, int, int)
    + {static} getInstance(int, int, int, int, int): HeroAircraft
    + forward(): void
    + shoot(): List<BaseBullet>
    + dropProp(): List<baseprop>
    + addHp(int): void
}

HeroAircraft --> HeroAircraft : 单例引用

@enduml
